import { Platform, StyleSheet } from "react-native";
import { withTheme } from "react-native-elements";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const customFonts = {
  "Comfortaa-Regular": require("../assets/fonts/Comfortaa-Regular.ttf"),
  "Comfortaa-Light": require("../assets/fonts/Comfortaa-Light.ttf"),
  "Comfortaa-Bold": require("../assets/fonts/Comfortaa-Bold.ttf"),
  "Comfortaa-Bold": require("./../assets/fonts/Comfortaa-Bold.ttf"),
  "Roboto-Thin": require("../assets/fonts/Roboto-Thin.ttf"),
  "Roboto-Bold": require("../assets/fonts/Roboto-Bold.ttf"),
  "Roboto-Regular": require("../assets/fonts/Roboto-Regular.ttf"),
  "Roboto-Light": require("../assets/fonts/Roboto-Light.ttf"),
};

export const firstRunStyles = StyleSheet.create({
  backgroundImageContainer: {
    flex: 1,
    resizeMode: "cover",
  },
  mainContainer: {
    flex: 1,
    alignSelf: "center",
    justifyContent: "space-between",
  },
  userContainer: {
    alignSelf: "center",
    marginTop: hp("14.5%"),
  },
  guestContainer: {
    alignSelf: "center",
    marginBottom: hp("10.5%"),
  },
});

export const radioButtonStyles = StyleSheet.create({
  priceValueContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: hp("0.25%"),
    alignSelf: "center",
    width: wp("75%"),
    borderBottomWidth: 1,
    borderColor: "white",
    backgroundColor: "#1e1c24",
    height: hp("4%"),
  },
  priceInputField: {
    alignSelf: "center",
    width: wp("40%"),
    paddingLeft: wp("1.5%"),
    fontSize: wp("4%"),
    fontFamily: "Roboto-Light",
    fontStyle: "italic",
    opacity: 0.8,
    color: "white",
  },
  priceCurrency: {
    flexDirection: "row",
  },
  radioText: {
    marginLeft: wp("3%"),
    paddingTop: hp("0.25%"),
    width: wp("8%"),
    fontSize: wp("3.5%"),
    fontFamily: "Roboto-Bold",
    opacity: 0.8,
    color: "#ededed",
  },
  radioCircle: {
    height: hp("2.25%"),
    width: hp("2.25%"),
    marginTop: hp("0.5%"),
    borderRadius: 100,
    borderWidth: 2,
    borderColor: "#87cefa",
    alignItems: "center",
    justifyContent: "center",
  },
  priceAgreementContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: hp("0.25%"),
    alignSelf: "center",
    width: wp("75%"),
    backgroundColor: "#1e1c24",
    height: hp("4%"),
  },
  agreementText: {
    marginLeft: wp("1.5%"),
    paddingTop: hp("0.25%"),
    width: wp("20%"),
    fontSize: wp("4%"),
    fontWeight: "bold",
    color: "#ededed",
  },
  selectedRb: {
    width: hp("1.25%"),
    height: hp("1.25%"),
    borderRadius: 50,
    backgroundColor: "#87cefa",
  },
});

export const errorStyle = {
  error: {
    borderWidth: 2,
    borderColor: "#ff102d",
    backgroundColor: "#1e1c24",
    color: "#ff102d",
  },
  adDescriptionButtonContainer: {
    alignSelf: "center",
    marginTop: hp("2%"),
    marginBottom: hp("2%"),
    width: wp("82%"),
    height: hp("4.25%"),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#ff102d",
    backgroundColor: "#1e1c24",
    opacity: 0.99,
    color: "#ff102d",
  },
  errorPlaceholder: {
    color: "#ff102d",
  },
  editProfileError: {
    borderBottomColor: "#ff102d",
    borderBottomWidth: 1,
  },
  fieldNameError: {
    color: "#ff102d",
  },
};

export const buttonsStyles = StyleSheet.create({
  logInButtonContainer: {
    width: wp("90%"),
    height: hp("9%"),
    borderRadius: 20,
    backgroundColor: "#1e1c24",
    opacity: 0.99,
  },
  logInButtonText: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("3%") : hp("1.75%"),
    color: "#ffffff",
    fontSize: wp("5.25%"),
    fontFamily: "Comfortaa-Bold",
  },
  signUpButtonContainer: {
    width: wp("90%"),
    height: hp("9%"),
    borderRadius: 20,
    backgroundColor: "#1e1c24",
    opacity: 0.99,
  },
  signUpButtonText: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("3%") : hp("1.75%"),
    color: "#ffffff",
    fontSize: wp("5.25%"),
    fontFamily: "Comfortaa-Bold",
  },
  firstRunButtonContainer: {
    width: wp("70%"),
    height: hp("37%"),
    borderRadius: 30,
    backgroundColor: "#1e1c24",
    opacity: 0.9,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 10,
  },
  inputImageHeight: {
    marginTop: hp("5%"),
    alignSelf: "center",
    width: hp("23%"),
    height: hp("23%"),
  },
  inputImageWidth: {
    marginTop: wp("9%"),
    alignSelf: "center",
    width: wp("45%"),
    height: wp("45%"),
  },
  firstRunButtonTextHeight: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("2%") : hp("1%"),
    color: "#ededed",
    fontSize: wp("7%"),
    fontFamily: "Comfortaa-Bold",
  },
  firstRunButtonTextWidth: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("3%") : hp("1.5%"),
    paddingTop: wp("3%"),
    color: "#ededed",
    fontSize: wp("7%"),
    fontFamily: "Comfortaa-Bold",
  },
  AdvButtonContainer: {
    alignSelf: "center",
    marginTop: hp("4%"),
    width: wp("92%"),
    height: hp("9%"),
    borderRadius: 20,
    backgroundColor: "#1e1c24",
    opacity: 0.99,
  },
  AdvButtonText: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("3%") : hp("1.5%"),
    color: "#ededed",
    fontSize: wp("5.25%"),
    fontFamily: "Comfortaa-Bold",
  },
  adDescriptionButtonContainer: {
    alignSelf: "center",
    marginTop: hp("2%"),
    width: wp("82%"),
    height: hp("6%"),
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "white",
    backgroundColor: "#1e1c24",
    opacity: 0.8,
  },
  adDescriptionButtonAdditional: {
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    width: wp("75%"),
  },
  adDescriptionButtonText: {
    textAlign: "center",
    paddingTop: hp("1.25%"),
    fontSize: wp("4%"),
    color: "#ededed",
    fontFamily: "Roboto-Light",
    fontStyle: "italic",
  },
  plusIcon: {
    fontSize: wp("4%"),
    color: "#ededed",
    paddingTop: hp("1.75%"),
  },
  editProfileButtonContainer: {
    alignSelf: "center",
    marginTop: hp("2.75%"),
    marginBottom: hp("1.75%"),
    width: wp("30%"),
    height: hp("4.25%"),
    borderRadius: 6,
    backgroundColor: "#5fd2ff",
    opacity: 0.99,
  },
  editProfileButtonText: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("0.75%") : hp("0.1%"),
    color: "#ffffff",
    fontSize: wp("4%"),
    fontFamily: "Comfortaa-Bold",
  },
  adButtonProfileContainer: {
    alignSelf: "center",
    marginTop: hp("2%"),
    marginBottom: hp("2%"),
    width: wp("50%"),
    height: hp("5.5%"),
    borderRadius: 6,
    backgroundColor: "#5fd2ff",
    opacity: 0.99,
  },
  adButtonProfileText: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("0.75%") : hp("0.1%"),
    color: "#ffffff",
    fontSize: wp("5.2%"),
    fontFamily: "Comfortaa-Bold",
  },
  aboutContactButtonContainer: {
    flexDirection: "row",
    alignContent: "center",
    alignSelf: "center",
    width: wp("80%"),
    height: hp("9%"),
    borderRadius: 20,
    backgroundColor: "#1e1c24",
    opacity: 0.99,
  },
  aboutContactIcon: {
    marginLeft: wp("12%"),
    paddingTop: Platform.OS === "ios" ? hp("2.75%") : hp("2.8%"),
    fontSize: wp("5%"),
    color: "#ededed",
  },
  aboutContactText: {
    textAlign: "center",
    paddingTop: Platform.OS === "ios" ? hp("2.75%") : hp("1.7%"),
    marginLeft: wp("2%"),
    color: "#ededed",
    fontSize: wp("5%"),
    fontFamily: "Comfortaa-Bold",
  },
});

export const headerStyles = StyleSheet.create({
  header: {
    width: "100%",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    fontFamily: "Comfortaa-Bold",
    fontSize: wp("5.25%"),
    color: "#ededed",
    letterSpacing: 1,
    marginLeft: -60,
  },
  headerTextMain: {
    fontFamily: "Comfortaa-Bold",
    fontSize: wp("5.25%"),
    color: "#ededed",
    letterSpacing: 1,
  },
  headerLogoMain: {
    paddingTop: hp("3%"),
    height: hp("3.2%"),
    width: hp("22%"),
  },
  headerLogo: {
    paddingTop: hp("3%"),
    height: hp("3.2%"),
    width: hp("22%"),
    marginLeft: Platform.OS === "ios" ? 0 : -60,
  },
  icon: {
    position: "absolute",
    left: Platform.OS === "ios" ? -wp("10%") : wp("2%"),
    color: "#ededed",
    fontSize: wp("7%"),
  },
  avatar: {
    height: hp("7%"),
    width: hp("7%"),
    position: "absolute",
    right: wp("2%"),
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "white",
  },
});
