export const USER_ACTIONS = {
  UPDATE_USER: "UPDATE_USER",
  GET_USER_INFO: "GET_USER_INFO",
  REGISTER_USER: "REGISTER_USER"
};

export const USER_ACTIONS_ASYNC = {
  UPDATE_USER: "UPDATE_USER_ASYNC",
  GET_USER_INFO: "GET_USER_INFO_ASYNC",
  REGISTER_USER: "REGISTER_USER_ASYNC"
};

